import { z } from "zod"

export const CompensationType = {
  HOURLY: "hourly",
  MONTHLY: "monthly",
} as const

export type CompensationTypeValue = (typeof CompensationType)[keyof typeof CompensationType]

export const compensationTypeOptions = [
  CompensationType.HOURLY,
  CompensationType.MONTHLY,
] as const

const compensationTypeSet = new Set<string>(compensationTypeOptions)

export function isCompensationType(value: string): value is CompensationTypeValue {
  return compensationTypeSet.has(value)
}

export function normalizeCompensationType(
  value: string | null | undefined,
  fallback: CompensationTypeValue = CompensationType.MONTHLY
): CompensationTypeValue {
  const normalized = value?.trim().toLowerCase() ?? ""
  return isCompensationType(normalized) ? normalized : fallback
}

export const compensationTypeSchema = z.enum(compensationTypeOptions)

export const PathCompanyEventType = {
  START_RATE: "start_rate",
  RATE_INCREASE: "rate_increase",
  ANNUAL_INCREASE: "annual_increase",
  MID_YEAR_INCREASE: "mid_year_increase",
  PROMOTION: "promotion",
  END_OF_EMPLOYMENT: "end_of_employment",
} as const

export type PathCompanyEventTypeValue =
  (typeof PathCompanyEventType)[keyof typeof PathCompanyEventType]

export const pathCompanyEventTypeOptions = [
  PathCompanyEventType.START_RATE,
  PathCompanyEventType.RATE_INCREASE,
  PathCompanyEventType.ANNUAL_INCREASE,
  PathCompanyEventType.MID_YEAR_INCREASE,
  PathCompanyEventType.PROMOTION,
  PathCompanyEventType.END_OF_EMPLOYMENT,
] as const

const pathCompanyEventTypeSet = new Set<string>(pathCompanyEventTypeOptions)

export function isPathCompanyEventType(value: string): value is PathCompanyEventTypeValue {
  return pathCompanyEventTypeSet.has(value)
}

export function normalizePathCompanyEventType(
  value: string | null | undefined,
  fallback: PathCompanyEventTypeValue = PathCompanyEventType.RATE_INCREASE
): PathCompanyEventTypeValue {
  const normalized = value?.trim().toLowerCase() ?? ""

  if (normalized === "annual") {
    return PathCompanyEventType.ANNUAL_INCREASE
  }

  return isPathCompanyEventType(normalized) ? normalized : fallback
}

export const pathCompanyEventTypeSchema = z.enum(pathCompanyEventTypeOptions)

export const CurrencyCode = {
  USD: "USD",
  PEN: "PEN",
  EUR: "EUR",
  GBP: "GBP",
  MXN: "MXN",
  COP: "COP",
  CLP: "CLP",
  ARS: "ARS",
  BRL: "BRL",
  CAD: "CAD",
  AED: "AED",
  AFN: "AFN",
  ALL: "ALL",
  AMD: "AMD",
  ANG: "ANG",
  AOA: "AOA",
  AUD: "AUD",
  AWG: "AWG",
  AZN: "AZN",
  BAM: "BAM",
  BBD: "BBD",
  BDT: "BDT",
  BGN: "BGN",
  BHD: "BHD",
  BIF: "BIF",
  BMD: "BMD",
  BND: "BND",
  BOB: "BOB",
  BSD: "BSD",
  BTN: "BTN",
  BWP: "BWP",
  BYN: "BYN",
  BZD: "BZD",
  CDF: "CDF",
  CHF: "CHF",
  CNY: "CNY",
  CRC: "CRC",
  CUC: "CUC",
  CUP: "CUP",
  CVE: "CVE",
  CZK: "CZK",
  DJF: "DJF",
  DKK: "DKK",
  DOP: "DOP",
  DZD: "DZD",
  EGP: "EGP",
  ERN: "ERN",
  ETB: "ETB",
  FJD: "FJD",
  FKP: "FKP",
  GEL: "GEL",
  GHS: "GHS",
  GIP: "GIP",
  GMD: "GMD",
  GNF: "GNF",
  GTQ: "GTQ",
  GYD: "GYD",
  HKD: "HKD",
  HNL: "HNL",
  HRK: "HRK",
  HTG: "HTG",
  HUF: "HUF",
  IDR: "IDR",
  ILS: "ILS",
  INR: "INR",
  IQD: "IQD",
  IRR: "IRR",
  ISK: "ISK",
  JMD: "JMD",
  JOD: "JOD",
  JPY: "JPY",
  KES: "KES",
  KGS: "KGS",
  KHR: "KHR",
  KMF: "KMF",
  KPW: "KPW",
  KRW: "KRW",
  KWD: "KWD",
  KYD: "KYD",
  KZT: "KZT",
  LAK: "LAK",
  LBP: "LBP",
  LKR: "LKR",
  LRD: "LRD",
  LSL: "LSL",
  LYD: "LYD",
  MAD: "MAD",
  MDL: "MDL",
  MGA: "MGA",
  MKD: "MKD",
  MMK: "MMK",
  MNT: "MNT",
  MOP: "MOP",
  MRU: "MRU",
  MUR: "MUR",
  MVR: "MVR",
  MWK: "MWK",
  MYR: "MYR",
  MZN: "MZN",
  NAD: "NAD",
  NGN: "NGN",
  NIO: "NIO",
  NOK: "NOK",
  NPR: "NPR",
  NZD: "NZD",
  OMR: "OMR",
  PAB: "PAB",
  PGK: "PGK",
  PHP: "PHP",
  PKR: "PKR",
  PLN: "PLN",
  PYG: "PYG",
  QAR: "QAR",
  RON: "RON",
  RSD: "RSD",
  RUB: "RUB",
  RWF: "RWF",
  SAR: "SAR",
  SBD: "SBD",
  SCR: "SCR",
  SDG: "SDG",
  SEK: "SEK",
  SGD: "SGD",
  SHP: "SHP",
  SLE: "SLE",
  SLL: "SLL",
  SOS: "SOS",
  SRD: "SRD",
  SSP: "SSP",
  STN: "STN",
  SVC: "SVC",
  SYP: "SYP",
  SZL: "SZL",
  THB: "THB",
  TJS: "TJS",
  TMT: "TMT",
  TND: "TND",
  TOP: "TOP",
  TRY: "TRY",
  TTD: "TTD",
  TWD: "TWD",
  TZS: "TZS",
  UAH: "UAH",
  UGX: "UGX",
  UYU: "UYU",
  UZS: "UZS",
  VES: "VES",
  VND: "VND",
  VUV: "VUV",
  WST: "WST",
  XAF: "XAF",
  XCD: "XCD",
  XCG: "XCG",
  XDR: "XDR",
  XOF: "XOF",
  XPF: "XPF",
  XSU: "XSU",
  YER: "YER",
  ZAR: "ZAR",
  ZMW: "ZMW",
  ZWG: "ZWG",
  ZWL: "ZWL",
} as const

export type CurrencyCodeValue = (typeof CurrencyCode)[keyof typeof CurrencyCode]

export const currencyOptions = [
  "USD",
  "PEN",
  "EUR",
  "GBP",
  "MXN",
  "COP",
  "CLP",
  "ARS",
  "BRL",
  "CAD",
  "AED",
  "AFN",
  "ALL",
  "AMD",
  "ANG",
  "AOA",
  "AUD",
  "AWG",
  "AZN",
  "BAM",
  "BBD",
  "BDT",
  "BGN",
  "BHD",
  "BIF",
  "BMD",
  "BND",
  "BOB",
  "BSD",
  "BTN",
  "BWP",
  "BYN",
  "BZD",
  "CDF",
  "CHF",
  "CNY",
  "CRC",
  "CUC",
  "CUP",
  "CVE",
  "CZK",
  "DJF",
  "DKK",
  "DOP",
  "DZD",
  "EGP",
  "ERN",
  "ETB",
  "FJD",
  "FKP",
  "GEL",
  "GHS",
  "GIP",
  "GMD",
  "GNF",
  "GTQ",
  "GYD",
  "HKD",
  "HNL",
  "HRK",
  "HTG",
  "HUF",
  "IDR",
  "ILS",
  "INR",
  "IQD",
  "IRR",
  "ISK",
  "JMD",
  "JOD",
  "JPY",
  "KES",
  "KGS",
  "KHR",
  "KMF",
  "KPW",
  "KRW",
  "KWD",
  "KYD",
  "KZT",
  "LAK",
  "LBP",
  "LKR",
  "LRD",
  "LSL",
  "LYD",
  "MAD",
  "MDL",
  "MGA",
  "MKD",
  "MMK",
  "MNT",
  "MOP",
  "MRU",
  "MUR",
  "MVR",
  "MWK",
  "MYR",
  "MZN",
  "NAD",
  "NGN",
  "NIO",
  "NOK",
  "NPR",
  "NZD",
  "OMR",
  "PAB",
  "PGK",
  "PHP",
  "PKR",
  "PLN",
  "PYG",
  "QAR",
  "RON",
  "RSD",
  "RUB",
  "RWF",
  "SAR",
  "SBD",
  "SCR",
  "SDG",
  "SEK",
  "SGD",
  "SHP",
  "SLE",
  "SLL",
  "SOS",
  "SRD",
  "SSP",
  "STN",
  "SVC",
  "SYP",
  "SZL",
  "THB",
  "TJS",
  "TMT",
  "TND",
  "TOP",
  "TRY",
  "TTD",
  "TWD",
  "TZS",
  "UAH",
  "UGX",
  "UYU",
  "UZS",
  "VES",
  "VND",
  "VUV",
  "WST",
  "XAF",
  "XCD",
  "XCG",
  "XDR",
  "XOF",
  "XPF",
  "XSU",
  "YER",
  "ZAR",
  "ZMW",
  "ZWG",
  "ZWL",
] as const

const currencyCodeSet = new Set<string>(currencyOptions)

export function isCurrencyCode(value: string): value is CurrencyCodeValue {
  return currencyCodeSet.has(value)
}

export function normalizeCurrencyCode(
  value: string | null | undefined,
  fallback: CurrencyCodeValue = CurrencyCode.USD
): CurrencyCodeValue {
  const normalized = value?.trim().toUpperCase() ?? ""
  return isCurrencyCode(normalized) ? normalized : fallback
}

export const currencyCodeSchema = z
  .string()
  .trim()
  .transform((value) => value.toUpperCase())
  .refine((value): boolean => isCurrencyCode(value), {
    message: "currency must be a supported ISO-4217 code",
  })

export const currencyMinorUnitsByCode: Record<CurrencyCodeValue, number> = {
  AED: 2,
  AFN: 0,
  ALL: 0,
  AMD: 2,
  ANG: 2,
  AOA: 2,
  ARS: 2,
  AUD: 2,
  AWG: 2,
  AZN: 2,
  BAM: 2,
  BBD: 2,
  BDT: 2,
  BGN: 2,
  BHD: 3,
  BIF: 0,
  BMD: 2,
  BND: 2,
  BOB: 2,
  BRL: 2,
  BSD: 2,
  BTN: 2,
  BWP: 2,
  BYN: 2,
  BZD: 2,
  CAD: 2,
  CDF: 2,
  CHF: 2,
  CLP: 0,
  CNY: 2,
  COP: 2,
  CRC: 2,
  CUC: 2,
  CUP: 2,
  CVE: 2,
  CZK: 2,
  DJF: 0,
  DKK: 2,
  DOP: 2,
  DZD: 2,
  EGP: 2,
  ERN: 2,
  ETB: 2,
  EUR: 2,
  FJD: 2,
  FKP: 2,
  GBP: 2,
  GEL: 2,
  GHS: 2,
  GIP: 2,
  GMD: 2,
  GNF: 0,
  GTQ: 2,
  GYD: 2,
  HKD: 2,
  HNL: 2,
  HRK: 2,
  HTG: 2,
  HUF: 2,
  IDR: 2,
  ILS: 2,
  INR: 2,
  IQD: 0,
  IRR: 0,
  ISK: 0,
  JMD: 2,
  JOD: 3,
  JPY: 0,
  KES: 2,
  KGS: 2,
  KHR: 2,
  KMF: 0,
  KPW: 0,
  KRW: 0,
  KWD: 3,
  KYD: 2,
  KZT: 2,
  LAK: 0,
  LBP: 0,
  LKR: 2,
  LRD: 2,
  LSL: 2,
  LYD: 3,
  MAD: 2,
  MDL: 2,
  MGA: 0,
  MKD: 2,
  MMK: 0,
  MNT: 2,
  MOP: 2,
  MRU: 2,
  MUR: 2,
  MVR: 2,
  MWK: 2,
  MXN: 2,
  MYR: 2,
  MZN: 2,
  NAD: 2,
  NGN: 2,
  NIO: 2,
  NOK: 2,
  NPR: 2,
  NZD: 2,
  OMR: 3,
  PAB: 2,
  PEN: 2,
  PGK: 2,
  PHP: 2,
  PKR: 2,
  PLN: 2,
  PYG: 0,
  QAR: 2,
  RON: 2,
  RSD: 0,
  RUB: 2,
  RWF: 0,
  SAR: 2,
  SBD: 2,
  SCR: 2,
  SDG: 2,
  SEK: 2,
  SGD: 2,
  SHP: 2,
  SLE: 2,
  SLL: 0,
  SOS: 0,
  SRD: 2,
  SSP: 2,
  STN: 2,
  SVC: 2,
  SYP: 0,
  SZL: 2,
  THB: 2,
  TJS: 2,
  TMT: 2,
  TND: 3,
  TOP: 2,
  TRY: 2,
  TTD: 2,
  TWD: 2,
  TZS: 2,
  UAH: 2,
  UGX: 0,
  USD: 2,
  UYU: 2,
  UZS: 2,
  VES: 2,
  VND: 0,
  VUV: 0,
  WST: 2,
  XAF: 0,
  XCD: 2,
  XCG: 2,
  XDR: 2,
  XOF: 0,
  XPF: 0,
  XSU: 2,
  YER: 0,
  ZAR: 2,
  ZMW: 2,
  ZWG: 2,
  ZWL: 2,
}

interface CompensationStepConfig {
  hourly: number
  monthly: number
}

// Keep historical UX compatibility for currencies already used in the app.
export const compensationStepOverrides: Partial<Record<CurrencyCodeValue, CompensationStepConfig>> = {
  USD: { hourly: 0.5, monthly: 100 },
  PEN: { hourly: 0.5, monthly: 100 },
  EUR: { hourly: 0.5, monthly: 100 },
  GBP: { hourly: 0.5, monthly: 100 },
  MXN: { hourly: 5, monthly: 500 },
  COP: { hourly: 1000, monthly: 100000 },
  CLP: { hourly: 500, monthly: 50000 },
  ARS: { hourly: 1000, monthly: 100000 },
  BRL: { hourly: 1, monthly: 100 },
  CAD: { hourly: 0.5, monthly: 100 },
}

function stepFromMinorUnits(minorUnits: number): CompensationStepConfig {
  const normalizedMinorUnits = Math.max(0, Math.min(3, Math.trunc(minorUnits)))
  const hourly = Number((1 / 10 ** normalizedMinorUnits).toFixed(6))

  if (normalizedMinorUnits === 0) {
    return { hourly, monthly: 100 }
  }

  if (normalizedMinorUnits === 3) {
    return { hourly, monthly: 0.1 }
  }

  return { hourly, monthly: 1 }
}

export function getCompensationRateStep(
  compensationType: CompensationTypeValue,
  currency: string
): number {
  const normalizedCurrency = normalizeCurrencyCode(currency)
  const override = compensationStepOverrides[normalizedCurrency]

  if (override) {
    return override[compensationType]
  }

  const minorUnits = currencyMinorUnitsByCode[normalizedCurrency] ?? 2
  const fallbackConfig = stepFromMinorUnits(minorUnits)

  return fallbackConfig[compensationType]
}
